version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: shouta
      POSTGRES_PASSWORD: shouta
      POSTGRES_DB: shouta
    restart: always
    networks:
      - shiftlab
networks:
  shiftlab:
